version: '3.5'

services:
  web_server:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app

  app:
    container_name: flask
    build:
      context: app
      dockerfile: Dockerfile
    env_file: db/database.conf
    expose:
      - 8080
    depends_on:
      - database

  database:
    container_name: postgres
    build:
      context: db
      dockerfile: Dockerfile
    env_file: db/database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
